---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: sre-pg
spec:
  releaseName: influxdb
  chart:
    repository: https://influxdata.github.io/helmcharts
    name: influxdb
    version: 4.8.5
  values:
    usePassword: true  
    
   
